package de.si.backdroplibrary

enum class BackdropEvent {
    // Backdrop content
    PREFETCH_BACKDROP_CONTENT_VIEW,
    SHOW_BACKDROP_CONTENT,
    HIDE_BACKDROP_CONTENT,
    BACKDROP_CONTENT_VISIBLE,
    BACKDROP_CONTENT_INVISIBLE,

    // titles
    CHANGE_TITLE,
    CHANGE_SUBTITLE,
    CLEAR_TITLE,
    CLEAR_SUBTITLE,

    // actions
    ACTIVATE_PRIMARY_ACTION,
    DEACTIVATE_PRIMARY_ACTION,
    ACTIVATE_MORE_ACTION,
    DEACTIVATE_MORE_ACTION,
    PRIMARY_ACTION_TRIGGERED,
    MORE_ACTION_TRIGGERED,

    // card stack
}