package de.si.backdroplibrary

enum class Event {
    // Backdrop content
    PREFETCH_BACKDROP_CONTENT_VIEW,
    SHOW_BACKDROP_CONTENT,
    HIDE_BACKDROP_CONTENT,
    BACKDROP_CONTENT_VISIBLE,
    BACKDROP_CONTENT_INVISIBLE,

    // titles
//    CHANGE_TITLE,
//    CHANGE_SUBTITLE,
//    CLEAR_TITLE,
//    CLEAR_SUBTITLE,

    // toolbar
    PRIMARY_ACTION_TRIGGERED,
    MORE_ACTION_TRIGGERED,
    CHANGE_NAVIGATION_ITEM,

    // card stack
    ADD_TOP_CARD,
    REMOVE_TOP_CARD
}